# Generated by Django 4.2.27 on 2025-12-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsapp', '0008_school_dos_theology_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='contact',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_image',
            field=models.FileField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
