# Generated by Django 4.2.27 on 2025-12-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsapp', '0009_school_contact_student_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='quran_marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
