# Generated by Django 4.2.27 on 2025-12-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsapp', '0011_student_fighu_grade_student_fighu_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
