# Generated by Django 4.2.27 on 2025-12-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsapp', '0012_student_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='content_2',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
