# Generated by Django 4.2.27 on 2025-12-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultsapp', '0013_about_us_content_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_us',
            name='content_3',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
    ]
